plugins/modules/vpc.py, plugins/modules/vpc_info.py, tests/integration/targets/cleanup/tasks/cleanup_vpc.yml, tests/integration/targets/vpc/aliases, tests/integration/targets/vpc/defaults/main.yml, tests/integration/targets/vpc/meta/main.yml, tests/integration/targets/vpc/tasks/main.yml, tests/integration/targets/vpc/tasks/tests.yml, tests/integration/targets/vpc_info/aliases, tests/integration/targets/vpc_info/defaults/main.yml, tests/integration/targets/vpc_info/meta/main.yml, tests/integration/targets/vpc_info/tasks/main.yml, tests/integration/targets/vpc_info/tasks/tests.yml
implement vpc, vpc_info  modules
=> implement vpc, vpc_info  modules

meta/runtime.yml, plugins/modules/firewall_rule_info.py, tests/integration/targets/firewall_rule_info/aliases, tests/integration/targets/firewall_rule_info/defaults/main.yml, tests/integration/targets/firewall_rule_info/meta/main.yml, tests/integration/targets/firewall_rule_info/tasks/main.yml, tests/integration/targets/firewall_rule_info/tasks/tests.yml
add new module firewall_rule_info
=> add firewall_rule_info

changelogs/fragments/block_type_block_storage.yml, plugins/modules/block_storage.py, plugins/modules/block_storage_info.py, tests/integration/targets/block_storage/defaults/main.yml, tests/integration/targets/block_storage/tasks/tests.yml, tests/integration/targets/block_storage/tasks/tests_attach_to_server.yml, tests/integration/targets/block_storage_info/defaults/main.yml, tests/integration/targets/block_storage_info/tasks/tests.yml
replaces #26, closes #25 
/cc @insanity54
=> block_storage: added param block_type

changelogs/fragments/instance-feature-handling.yml, plugins/module_utils/vultr_v2.py, plugins/modules/instance.py, tests/integration/targets/instance/defaults/main.yml, tests/integration/targets/instance/tasks/present.yml
backups should be either `enabled` or `disabled` on instance creation. also see https://www.vultr.com/de/api/#operation/create-instance
See #30
=> instance: refactor to fix backups on create

changelogs/fragments/instance-ssh-key.yml, plugins/modules/instance.py
ssh keys were ignored (see https://www.vultr.com/de/api/#operation/create-instance)
closes #35
=> instance: fix ssh keys not handled

.github/workflows/unit.yml, plugins/inventory/vultr.py
=> doc: inventory: clarify file endings

plugins/module_utils/vultr_v2.py
transform is executed not only for the "main" resource but every queried resource using `query_filter_list_by_name` . This is problematic in the instance module, in which we query different resources for OS name, firewall group or startup script. 
We ensure, transformation is only enabled for the main resource query using a `skip_tranform` (default=True) argument.
=> instance: fix transformation not skippable

changelogs/fragments/instance-vpcs.yml, plugins/modules/instance.py, tests/integration/targets/instance/defaults/main.yml, tests/integration/targets/instance/tasks/failures.yml, tests/integration/targets/instance/tasks/main.yml, tests/integration/targets/instance/tasks/present.yml, tests/integration/targets/instance/tasks/tests.yml
depends on #45 
closes #23 
Implement VPCs handing in instance.
=> Implement VPCs handling in instances

plugins/module_utils/vultr_v2.py, plugins/modules/instance_info.py, tests/integration/targets/instance_info/aliases, tests/integration/targets/instance_info/defaults/main.yml, tests/integration/targets/instance_info/meta/main.yml, tests/integration/targets/instance_info/tasks/main.yml, tests/integration/targets/instance_info/tasks/tests.yml
new instance_info module.
closes #47
=> new module instance_info

changelogs/fragments/instance_info-runtime.yml, meta/runtime.yml
instance_info: fix module missing in action group
=> instance_info: fix module missing in action group

changelogs/instance-script-id.yml, plugins/module_utils/vultr_v2.py, plugins/modules/instance.py
Fix start script being ignored
Fixes #49
=> instance: fix start script ignored

plugins/inventory/vultr.py
Doesn't fix #52 yet, but at least this documents the helpful workaround suggested by @resmo
#52
=> document the quick fix how to connect via main_ip

plugins/modules/snapshot.py, plugins/modules/snapshot_info.py, tests/integration/targets/cleanup/tasks/cleanup_snapshot.yml, tests/integration/targets/snapshot/aliases, tests/integration/targets/snapshot/defaults/main.yml, tests/integration/targets/snapshot/meta/main.yml, tests/integration/targets/snapshot/tasks/absent.yml, tests/integration/targets/snapshot/tasks/failures.yml, tests/integration/targets/snapshot/tasks/main.yml, tests/integration/targets/snapshot/tasks/present.yml, tests/integration/targets/snapshot/tasks/tests.yml, tests/integration/targets/snapshot_info/aliases, tests/integration/targets/snapshot_info/defaults/main.yml, tests/integration/targets/snapshot_info/meta/main.yml, tests/integration/targets/snapshot_info/tasks/main.yml, tests/integration/targets/snapshot_info/tasks/tests.yml
snapshot and snapshot_info modules
closes #57
=> implement snapshot, snapshot_info

tests/integration/targets/instance/defaults/main.yml
image does not exist anymore
#59
=> ci: instance: fix image does not exist

changelogs/fragments/68-instance-locked-absent.yml, plugins/module_utils/vultr_v2.py, plugins/modules/instance.py
instances can not be deleted if locked, wait for unlock before delete
#59
=> instance: wait for unlock on absent

changelogs/fragments/70-inventory-fix-tags-not-returned.yml, plugins/inventory/vultr.py
tags attribute was not returned, broken example in inventory doc
#69
=> inventory: fix missing tags attribute

changelogs/fragments/instance-reinstall.yml, plugins/doc_fragments/vultr_v2.py, plugins/module_utils/vultr_v2.py, plugins/modules/instance.py, plugins/modules/snapshot.py, tests/integration/targets/cleanup/tasks/cleanup_vpc.yml, tests/integration/targets/instance/tasks/reinstall.yml, tests/integration/targets/instance/tasks/tests.yml
implement state reinstalled, needs tests.
Closes to #65
=> instance: add state reinstalled

plugins/modules/dns_domain_info.py, plugins/modules/instance_info.py
fix typos in examples
fixes #72
=> doc: fix typos in examples

plugins/module_utils/vultr_v2.py, plugins/modules/dns_record.py, plugins/modules/user.py
=> doc: fix boolean values to be true/false

meta/runtime.yml, plugins/modules/vpc2.py, plugins/modules/vpc2_info.py, tests/integration/targets/cleanup/tasks/cleanup_vpc2.yml, tests/integration/targets/vpc2/aliases, tests/integration/targets/vpc2/defaults/main.yml, tests/integration/targets/vpc2/meta/main.yml, tests/integration/targets/vpc2/tasks/main.yml, tests/integration/targets/vpc2/tasks/tests.yml, tests/integration/targets/vpc2_info/aliases, tests/integration/targets/vpc2_info/defaults/main.yml, tests/integration/targets/vpc2_info/meta/main.yml, tests/integration/targets/vpc2_info/tasks/main.yml, tests/integration/targets/vpc2_info/tasks/tests.yml
=> [Feature] add VPC 2.0 support

meta/runtime.yml, plugins/module_utils/common_instance.py, plugins/module_utils/vultr_v2.py, plugins/modules/bare_metal.py, plugins/modules/instance.py, tests/integration/targets/bare_metal/aliases, tests/integration/targets/bare_metal/defaults/main.yml, tests/integration/targets/bare_metal/meta/main.yml, tests/integration/targets/bare_metal/tasks/absent.yml, tests/integration/targets/bare_metal/tasks/failures.yml, tests/integration/targets/bare_metal/tasks/main.yml, tests/integration/targets/bare_metal/tasks/present.yml, tests/integration/targets/bare_metal/tasks/tests.yml, tests/integration/targets/cleanup/tasks/cleanup_bare_metal.yml, tests/integration/targets/cleanup/tasks/cleanup_vpc2.yml, tests/integration/targets/instance/tasks/failures.yml
=> add bare_metal module, refactors instance

changelogs/fragments/86-inventory-internal_ip.yml, plugins/inventory/vultr.py, tests/unit/plugins/inventory/test_vultr.py
Add `internal_ip` to the attributes
#86
=> inventory: add internal_ip attribute

tests/integration/targets/block_storage_info/tasks/tests.yml, tests/integration/targets/dns_domain_info/tasks/tests.yml, tests/integration/targets/dns_record/tasks/create_record.yml, tests/integration/targets/dns_record/tasks/remove_record.yml, tests/integration/targets/dns_record/tasks/update_record.yml, tests/integration/targets/firewall_group_info/tasks/tests.yml, tests/integration/targets/firewall_rule/tasks/rule_absent.yml, tests/integration/targets/firewall_rule/tasks/rule_present.yml, tests/integration/targets/firewall_rule_info/tasks/tests.yml, tests/integration/targets/instance/tasks/present.yml, tests/integration/targets/instance_info/tasks/tests.yml, tests/integration/targets/snapshot_info/tasks/tests.yml, tests/integration/targets/ssh_key_info/tasks/tests.yml, tests/integration/targets/startup_script_info/tasks/tests.yml, tests/integration/targets/vpc2_info/tasks/tests.yml, tests/integration/targets/vpc_info/tasks/tests.yml
fix breaking changes in ansible related to CVE-2023-5764 affecting CI tests
=> fix conditional statements should not include jinja2 templating delimiters

changelogs/fragments/102-state-detect.yml, plugins/module_utils/vultr_v2.py
=> fix wait for state detection

meta/runtime.yml, plugins/modules/object_storage.py, tests/integration/targets/cleanup/tasks/cleanup_object_storage.yml, tests/integration/targets/object_storage/aliases, tests/integration/targets/object_storage/defaults/main.yml, tests/integration/targets/object_storage/tasks/failures.yml, tests/integration/targets/object_storage/tasks/main.yml, tests/integration/targets/object_storage/tasks/tests.yml
=> new module object storage

plugins/module_utils/vultr_v2.py
=> show retries in request error msg

plugins/doc_fragments/vultr_v2.py, tests/integration/targets/instance/tasks/absent.yml
instance: increase retries for state=absent
#113
=> test: instance: increase retries for state=absent

tests/integration/targets/cleanup/tasks/cleanup_vpc.yml, tests/integration/targets/instance/defaults/main.yml, tests/integration/targets/instance/tasks/tests.yml
gitlab app needs at least 2 cores
#116
=> test: fix use plan with >=2c for gitlab app

changelogs/fragments/instance-skip_wait.yml, plugins/module_utils/vultr_v2.py, plugins/modules/bare_metal.py, plugins/modules/instance.py
allow to skip waiting on user demand to fast forward things
#119
=> instance, bare_metal: allow to skip waiting

meta/runtime.yml, plugins/modules/block_storage.py, plugins/modules/object_storage.py, plugins/modules/object_storage_cluster_info.py, plugins/modules/object_storage_info.py, tests/integration/targets/object_storage/defaults/main.yml, tests/integration/targets/object_storage_cluster_info/aliases, tests/integration/targets/object_storage_cluster_info/tasks/main.yml, tests/integration/targets/object_storage_info/aliases, tests/integration/targets/object_storage_info/defaults/main.yml, tests/integration/targets/object_storage_info/tasks/main.yml, tests/integration/targets/object_storage_info/tasks/tests.yml, tests/integration/targets/os_info/tasks/main.yml
=> Add object_storage_info module

plugins/modules/dns_domain.py, tests/integration/targets/dns_domain/tasks/tests.yml
=> Issue #140 - Remove requirement for the ip argument when creating a new domain

plugins/modules/load_balancer.py, plugins/modules/load_balancer_info.py, tests/integration/targets/load_balancer/aliases, tests/integration/targets/load_balancer/defaults/main.yml, tests/integration/targets/load_balancer/tasks/main.yml, tests/integration/targets/load_balancer/tasks/tests.yml
Adding Tests and Modules to Ansible collection for Vultr Load Balancer
=> Adding Load Balancers to Ansible Collection

tests/integration/targets/snapshot/defaults/main.yml, tests/integration/targets/snapshot/tasks/tests.yml, tests/integration/targets/user/tasks/tests.yml, tests/integration/targets/user_info/tasks/tests.yml
More fixes for integration tests that currently fail
@resmo - I took two of the fixes from your PR since they aren't technically related to the state of instances.
I'll take a look at #135 which should also leave us with only the instance state issue keeping us from having passing integration tests again
Related to #131
=> Issue 131: Additional integration test fixes

plugins/modules/object_storage.py, tests/integration/targets/cleanup/tasks/cleanup_load_balancer.yml, tests/integration/targets/load_balancer/defaults/main.yml, tests/integration/targets/load_balancer/tasks/main.yml, tests/integration/targets/load_balancer/tasks/tests.yml
- Fixes sanity test for object_storage module tier defaults
- Adds proper cleanup for load balancer tests
- Disables failing tests
___
Bug fix, Tests
___
- Add default `Legacy` tier to object_storage module
- Create cleanup role for load balancer tests
- Disable failing load balancer tests
- Update test labels to use resource prefix
___
```mermaid
flowchart LR
A["object_storage.py"] -->|"add default tier"| B["Legacy"]
C["cleanup_load_balancer.yml"] -->|"remove test resources"| D["API cleanup"]
E["tests.yml"] -->|"disable failing tests"| F["skip execution"]
```
<details> <summary><h3> File Walkthrough</h3></summary>
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
<td>
<details> …
=> More integration test fixes for #131
